### ISSUE TITLE
When click Search received UnknownHost Exception

### ISSUE THREAD

**Issue by jyanosyjr** [gatemezing/ProLOV#5]
Received a java.net.UnknownHostException: lov.okfn.org after "Initiializing LOV view" in plugin.

**Comment by NuriaGarcia** [comment]
Hello,

If you check now the problem follows happening?, because now I test the
plugin and it is working right. Maybe in that moment LOV tool was down.

Thanks.

Best regards!

Nuria Garcia

2016-02-05 22:00 GMT+01:00 jyanosyjr notifications@github.com:
